### ISSUE TITLE
Repository URL?

### ISSUE THREAD

**Issue by ibigfire** [Maia-Everett/dalamud-roleplay-profiles#1]
Hi, super sorry if this is obvious and I'm asking a dumb question.  But I really miss roleplay profiles, is there a repository URL somewhere for this so I could add it myself?

**Comment by Maia-Everett** [comment]
It should be in the main Dalamud repository. I wasn't aware of it ever being removed. Let me check.

**Comment by ibigfire** [comment]
My mistake, I'm sorry.  I do see it there, I got it confused for another plugin that shows profiles for various websites.  That plugin just hasn't been updated in a while so it no longer shows up, and I thought maybe it had been booted off of the main repository and I got mixed up when I found this one.

Thank you for your creation of this plugin, it's still showing up fine.  I hope you're having a lovely day!
